### PR TITLE
Himanshu/spinner

### PR DESCRIPTION
**Pull request by HGoyal09**
image
image

### CODE REVIEW

**Comment by raghavthakur** [comment]
The spinner would look cleaner if there was no border around it, just the spinner by itself, like how Apple does it.

**Review by raghavthakur — DISMISSED** [review]
Might want to reformat with the prettier config file if not already done so.

**Comment by weiyoung** [comment]
> The spinner would look cleaner if there was no border around it, just the spinner by itself, like how Apple does it.

yup I agree! I can make the changes

**Comment by raghavthakur** [comment]
Sure. Let me know when I should review again.

**Comment by paulsgh** [comment]
Spinner is not centred for me (this is the case on all pages with the spinner).

spinner

**Comment by raghavthakur** [comment]
I can also confirm that the spinner is not centred.
Screen Shot 2021-08-04 at 6 24 18 PM

**Pull request closed without merging**
